const wordCategories = {
  animals: {
    name: "Animals",
    words: [
      "cat",
      "dog",
      "rabbit",
      "elephant",
      "giraffe",
      "kangaroo",
      "lion",
      "zebra",
      "panda",
      "bear",
    ],
  },
  food: {
    name: "Food",
    words: [
      "apple",
      "banana",
      "carrot",
      "pizza",
      "burger",
      "pasta",
      "salad",
      "cake",
      "bread",
      "cheese",
    ],
  },
  tools: {
    name: "Tools",
    words: [
      "hammer",
      "wrench",
      "screwdriver",
      "drill",
      "saw",
      "pliers",
      "chisel",
      "level",
      "tape measure",
      "axe",
    ],
  },
  colors: {
    name: "Colors",
    words: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "black",
      "white",
      "pink",
      "brown",
    ],
  },
  vehicles: {
    name: "Vehicles",
    words: [
      "car",
      "truck",
      "bicycle",
      "motorcycle",
      "airplane",
      "boat",
      "train",
      "bus",
      "scooter",
      "helicopter",
    ],
  },
  professions: {
    name: "Professions",
    words: [
      "doctor",
      "teacher",
      "engineer",
      "chef",
      "pilot",
      "nurse",
      "police",
      "artist",
      "writer",
      "lawyer",
    ],
  },
  householdItems: {
    name: "Household Items",
    words: [
      "chair",
      "table",
      "sofa",
      "bed",
      "lamp",
      "fridge",
      "microwave",
      "toaster",
      "clock",
      "curtain",
    ],
  },
  sports: {
    name: "Sports",
    words: [
      "soccer",
      "basketball",
      "tennis",
      "cricket",
      "baseball",
      "golf",
      "hockey",
      "volleyball",
      "rugby",
      "swimming",
    ],
  },
  countries: {
    name: "Countries",
    words: [
      "USA",
      "Canada",
      "Germany",
      "France",
      "Japan",
      "India",
      "Brazil",
      "Australia",
      "China",
      "Italy",
    ],
  },
};

console.log(wordCategories);
