export const wordCategories = {
  animals: {
    name: "Animals",
    words: [
      "cat",
      "dog",
      "rabbit",
      "elephant",
      "giraffe",
      "kangaroo",
      "lion",
      "zebra",
      "panda",
      "bear",
      "tiger",
      "penguin",
      "koala",
      "dolphin",
      "shark",
      "monkey",
      "gorilla",
      "snake",
      "eagle",
      "owl",
    ],
  },
  food: {
    name: "Food",
    words: [
      "apple",
      "banana",
      "carrot",
      "pizza",
      "burger",
      "pasta",
      "salad",
      "cake",
      "bread",
      "cheese",
      "sushi",
      "taco",
      "ice cream",
      "chocolate",
      "sandwich",
      "noodles",
      "steak",
      "soup",
      "rice",
      "pancake",
    ],
  },
  tools: {
    name: "Tools",
    words: [
      "hammer",
      "wrench",
      "screwdriver",
      "drill",
      "saw",
      "pliers",
      "chisel",
      "level",
      "tape measure",
      "axe",
    ],
  },
  colors: {
    name: "Colors",
    words: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "black",
      "white",
      "pink",
      "brown",
    ],
  },
  vehicles: {
    name: "Vehicles",
    words: [
      "car",
      "truck",
      "bicycle",
      "motorcycle",
      "airplane",
      "boat",
      "train",
      "bus",
      "scooter",
      "helicopter",
    ],
  },
  professions: {
    name: "Professions",
    words: [
      "doctor",
      "teacher",
      "engineer",
      "chef",
      "pilot",
      "nurse",
      "police",
      "artist",
      "writer",
      "lawyer",
    ],
  },
  householdItems: {
    name: "Household Items",
    words: [
      "chair",
      "table",
      "sofa",
      "bed",
      "lamp",
      "fridge",
      "microwave",
      "toaster",
      "clock",
      "curtain",
    ],
  },
  sports: {
    name: "Sports",
    words: [
      "soccer",
      "basketball",
      "tennis",
      "cricket",
      "baseball",
      "golf",
      "hockey",
      "volleyball",
      "rugby",
      "swimming",
    ],
  },
  countries: {
    name: "Countries",
    words: [
      "USA",
      "Canada",
      "Germany",
      "France",
      "Japan",
      "India",
      "Brazil",
      "Australia",
      "China",
      "Italy",
    ],
  },
  technology: {
    name: "Technology",
    words: [
      "smartphone",
      "laptop",
      "tablet",
      "smartwatch",
      "headphones",
      "router",
      "keyboard",
      "mouse",
      "printer",
      "monitor",
      "camera",
      "drone",
      "robot",
      "server",
      "battery",
      "charger",
      "speaker",
      "microphone",
      "console",
      "projector",
    ],
  },
  emotions: {
    name: "Emotions",
    words: [
      "happy",
      "sad",
      "angry",
      "excited",
      "nervous",
      "confused",
      "surprised",
      "scared",
      "proud",
      "jealous",
      "peaceful",
      "anxious",
      "grateful",
      "lonely",
      "confident",
      "worried",
      "amused",
      "frustrated",
      "loved",
      "bored",
    ],
  },
  movies: {
    name: "Movies",
    words: [
      "action",
      "comedy",
      "drama",
      "horror",
      "romance",
      "thriller",
      "animation",
      "documentary",
      "musical",
      "fantasy",
      "western",
      "sci-fi",
      "adventure",
      "mystery",
      "superhero",
      "classic",
      "indie",
      "blockbuster",
      "noir",
      "family",
    ],
  },
  superheroes: {
    name: "Superheroes",
    words: [
      "Superman",
      "Batman",
      "Spider-Man",
      "Wonder Woman",
      "Iron Man",
      "Thor",
      "Black Widow",
      "Hulk",
      "Flash",
      "Wolverine",
      "Captain America",
      "Black Panther",
      "Doctor Strange",
      "Deadpool",
      "Ant-Man",
      "Green Lantern",
      "Aquaman",
      "Vision",
      "Hawkeye",
      "Wasp",
    ],
  },
  videogames: {
    name: "Video Games",
    words: [
      "Minecraft",
      "Fortnite",
      "Mario",
      "Zelda",
      "Pacman",
      "Sonic",
      "Pokemon",
      "Tetris",
      "Portal",
      "Halo",
      "Doom",
      "Minecraft",
      "GTA",
      "FIFA",
      "Skyrim",
      "Witcher",
      "Overwatch",
      "Valorant",
      "Roblox",
      "Among Us",
    ],
  },
};
